# Generated by Django 4.2.5 on 2023-10-05 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_rename_xipcode_shippingaddress_zipcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
